graph LR
    subgraph トップ画面
        A[トップ画面] -->|商品表示| B{商品詳細画面}
        A -->|カテゴリリンク| C{カテゴリ商品一覧画面}
    end
    subgraph 商品詳細画面
        B -->|カートに入れるボタン| D{ショッピングカート画面}
    end
    subgraph カテゴリ商品一覧画面
        C -->|商品表示| B
    end
    subgraph ショッピングカート画面
        D -->|レジに進むボタン| F{ログイン画面}
        D -->|レジに進むボタン| G{お届け先入力画面}
    end
    subgraph ログイン画面
        F -->|ログインボタン| D
        F -->|ログインボタン| G
        F -->|新規登録ボタン| H{新規登録画面}
    end
    subgraph 新規登録画面
        H -->|登録するボタン| F
    end
    subgraph お届け先入力画面
        G -->|決済へ進む| I{決済情報入力画面}
    end
    subgraph 決済情報入力画面
        I -->|注文確認画面へ| J{注文確認画面}
    end
    subgraph 注文確認画面
        J -->|購入を確定するボタン| K{購入完了画面}
    end
    subgraph アカウント画面
        L{アカウント画面} -->|メールアドレスを変更するボタン| M{メールアドレス変更画面}
        L -->|パスワード変更するボタン| N{パスワード変更画面}
        L -->|名前 住所 電話番号　変更ボタン| O{名前 住所 電話番号変更画面}
        L -->|注文履歴ボタン| P{注文履歴画面}
    end
    subgraph メールアドレス変更画面
        M -->|変更するボタン| Q{メールアドレス変更確認メール送信}
        Q -->|確認メール内の確認リンク| R{メールアドレス変更完了画面}
    end
    subgraph メールアドレス変更完了画面
        R -->|戻る| L
    end
    subgraph パスワード変更画面
        N -->|変更するボタン| L
    end
    subgraph 名前 住所 電話番号変更画面
        O -->|変更するボタン| L
    end
    subgraph 注文履歴画面
        P -->|商品リンク| B
    end
    subgraph ウィッシュリスト画面
        E -->|カートに入れるボタン| D
        E -->|削除ボタン| E{ウイッシュリスト画面}
    end
